### ISSUE TITLE
How do you connect the lightbulb to the lan to begin with?

### ISSUE THREAD

**Issue by phillip-haydon** [LIFX/lifx-gem#4]
Looking through everything I can't seem to see anything which addresses the issue of connecting the lightbulb to the wifi. 

This is still seems completely useless for me since I do not have an iPhone or Android phone...

**Comment by ThrosturX** [comment]
Phillip, you can connect to your bulb with the lifx-console gem or with
```ruby
client = LIFX::Client.lan
begin
  client.discover! do |c|
    c.lights.first
  end
rescue LIFX::Client::DiscoveryTimeout
  $stderr.puts("None found")
  exit 1
end
```

**Comment by phillip-haydon** [comment]
@ThrosturX I threw the lifx bulb away, its basically useless without a proper API to play around with. The fact I need a device to just start using it with the API is hugely retarded. Had I known I would need a specific device to begin with I wouldn't have backed the project. I would have loved to have made a Windows Phone or Windows Store App for lifx. Such a shame.
