### ISSUE TITLE
Firmware 2.0 support?

### ISSUE THREAD

**Issue by ryanj** [LIFX/lifx-gem#47]
Does this library support the new 2.0 Firmware?  (no mesh networking)

With this library, I'm unable to find my lights, while the Android app works without issue.

**Comment by chendo** [comment]
Unfortunately we haven't had the time to update it yet but we will.

**Comment by bopm** [comment]
:+1: any predictions on long it'll take?

**Comment by dleffo** [comment]
I have the library working with firmware 2.0.  At one stage I needed to re-add the tags with light.add_tag() to each bulb to run any scripts that were run on a room, even though the iOS app had the group names in it.

i.e. Even though the iOS app had all the loungeroom lights in "Lounge", no scripts would find the loungeroom lights until I added the tag via a command line script as well.  I only needed to readd the tag once per bulb and then all good.  :+1:

**Comment by dotMorten** [comment]
wow an entire month where people are completely blocked? Well if only they would the very least publish the UDP protocols being used

**Comment by jmcgill** [comment]
Sub.

Bought LIFX over Hue for the API support; losing it with a firwmare update is a pretty big set back. Any ETA on a fix, or any indication as to what has changed so the community can propose a fix?

**Comment by chendo** [comment]
Unfortunately no ETA just yet. Currently the best way is to use the HTTP API: http://developer.lifx.com/

The downside is that it's not local, however it's fairly responsive still.

**Comment by mschuler** [comment]
But how to create a cloud account without iPhone or Android App?

**Comment by dotMorten** [comment]
@chendo that's no small downside. Opening up to the open web and a server I don't control is a huge security potential too - and it's not like you have a great history in this regard. And you still have to send your Wi-Fi password in clear text to an open Wi-Fi to get the bulb to connect to your own Wi-Fi. What were you thinking?

**Comment by dotMorten** [comment]
@mschuler it's clear that lifx only cares about IOS and android and completely forgot what they promised to deliver during their kickstarter. They couldn't care less if they support 1.5billion PCs too and think they can cop that out by announcing some AllJoyn support which win 10 will have some off (don't get me wrong - it's a good step but a long term one and only helping people using the new white only bulb)

**Comment by mschuler** [comment]
@dotMorten I'm the creator of the [LIFX App for windows Phone](http://www.windowsphone.com/de-de/store/app/my-lifx/5fbe26c5-1153-44a8-a8e4-5b757e354ad5). Unfortunately it's not working anymore since Firmware 2.0. And there is no public information what exactly they changed :-( Giving the possibility to register for a Cloud Account without Android or IPhone would open new possibilities for devs like me.

**Comment by dotMorten** [comment]
@mschuler I'm aware of your app and your library - but make either of them work even with a 1.5 lightbulb. I'm setting out to build a little larger HA system based on Win10, and can't really get anywhere with LIFX. Currently I'm completely blocked, because I don't own an Android phone, and my iPhone is an 4 edition that doesn't run iOS8 which is all the LIFX app supports now. So I can't even get the damn thing on my local network. I've been trying to reverse engineer based on other apps and LIFX's completely outdated sourcecode, but no luck so far.

**Comment by chendo** [comment]
@dotMorten The WiFi password is never sent in plain text. What are you talking about?

We care, unfortunately we have limited resources, so we can't build all the things we'd like.

@mschuler We're actively working on releasing protocol documentation, please hang on

**Comment by dotMorten** [comment]
@chendo Well I can't refer to your non-existent protocol documentation (but good to hear it's coming), but the reverse engineered document sure seem to indicate this: https://github.com/magicmonkey/lifxjs/blob/master/Protocol.md#0x131

**Comment by chendo** [comment]
@dotMorten That message is only valid during onboard stage, where communication to the bulb is secured via TLS

**Comment by cdl** [comment]
Sigh. Just bought a new LIFX solely for the really cool API support, updated my bulb to 2.0 excitedly once it arrived... and found this out. Sadly the HTTP API won't really work for me, as what I'd like to do with it is a little latency-sensitive (interface with a MIDI controller).

Please update this gem!

**Comment by ryanj** [comment]
Here is an alternative library with experimental 2.0 support, and some discussion on decoding the wire protocol:

https://github.com/magicmonkey/lifxjs/issues/34

**Comment by bopm** [comment]
@chendo are month enough to set ETA or just start fixing things?
